# Generated by Django 4.1.1 on 2023-11-08 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LuxCart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlisting',
            name='image',
            field=models.ImageField(default=0, upload_to='images'),
            preserve_default=False,
        ),
    ]
